// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultProductionFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3phCoQOIiDa4UFrvoSde-VMxrcMts4sw',
    appId: '1:933981857715:web:3ccdbf2a36760611194dc6',
    messagingSenderId: '933981857715',
    projectId: 'farmbov-742e9',
    authDomain: 'farmbov-742e9.firebaseapp.com',
    storageBucket: 'farmbov-742e9.appspot.com',
    measurementId: 'G-04VJV0L2RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTZVzH3h9DJQNlpHa64Xc3UjJHULh2K_0',
    appId: '1:933981857715:android:a9eef91959d0764f194dc6',
    messagingSenderId: '933981857715',
    projectId: 'farmbov-742e9',
    storageBucket: 'farmbov-742e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmroR6i4ET7brcp66VzBU75pnQSKftZX4',
    appId: '1:933981857715:ios:e71a541415bc4580194dc6',
    messagingSenderId: '933981857715',
    projectId: 'farmbov-742e9',
    storageBucket: 'farmbov-742e9.appspot.com',
    iosBundleId: 'br.ikhon.farmbov',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI4LSZAMvAQmezXPwl3X6h9dOG0zNX2vw',
    appId: '1:552219503152:web:987bb10374d38040095bf5',
    messagingSenderId: '552219503152',
    projectId: 'farmbov-af05a',
    authDomain: 'farmbov-af05a.firebaseapp.com',
    storageBucket: 'farmbov-af05a.appspot.com',
    measurementId: 'G-01BRJVC8TP',
  );
}
