// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultDevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI4LSZAMvAQmezXPwl3X6h9dOG0zNX2vw',
    appId: '1:552219503152:web:987bb10374d38040095bf5',
    messagingSenderId: '552219503152',
    projectId: 'farmbov-af05a',
    authDomain: 'farmbov-af05a.firebaseapp.com',
    storageBucket: 'farmbov-af05a.appspot.com',
    measurementId: 'G-01BRJVC8TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLyPR5gfRjmDjsLuqzby393GG48SD4pDs',
    appId: '1:552219503152:android:c531d972e3fe64a4095bf5',
    messagingSenderId: '552219503152',
    projectId: 'farmbov-af05a',
    storageBucket: 'farmbov-af05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOW95UGVHuf9SqcZhlFl8tbn3VTl4bdT4',
    appId: '1:552219503152:ios:3f5c97d733468c22095bf5',
    messagingSenderId: '552219503152',
    projectId: 'farmbov-af05a',
    storageBucket: 'farmbov-af05a.appspot.com',
    iosBundleId: 'br.ikhon.farmbov.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI4LSZAMvAQmezXPwl3X6h9dOG0zNX2vw',
    appId: '1:552219503152:web:987bb10374d38040095bf5',
    messagingSenderId: '552219503152',
    projectId: 'farmbov-af05a',
    authDomain: 'farmbov-af05a.firebaseapp.com',
    storageBucket: 'farmbov-af05a.appspot.com',
    measurementId: 'G-01BRJVC8TP',
  );
}
